import os
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Subset

from src.datasets import LungSurvivalDataset

# ======================
# PATHS
# ======================
RAW_CSV      = "data/multimodal_dataset.csv"
CLEAN_CSV    = "data/multimodal_dataset_clean.csv"    # deduplicated, all genes
AE_CSV       = "data/multimodal_dataset_ae.csv"       # 2000-gene AE input
CLINICAL_CSV = "data/clinical_features.csv"           # 4 encoded clinical features
ct_dir       = "data/ct_processed"
os.makedirs("trained_models", exist_ok=True)

# ======================
# DEDUPLICATION — single point of truth
# train_lung_model.py is the ONLY file that reads the raw CSV and writes
# the clean one. Every other file (predict.py, analyze_model.py, app.py)
# simply loads CLEAN_CSV directly without calling drop_duplicates itself.
#
# Note: build_multimodal_dataset.py now filters to primary tumour (-01*)
# samples before truncating patient IDs, preventing duplicates at source.
# This deduplication step is kept as a safety net in case the raw CSV
# was generated by an older version of build_multimodal_dataset.py.
# ======================
full_df = pd.read_csv(RAW_CSV, low_memory=False)
before  = len(full_df)
full_df = full_df.drop_duplicates(subset="patient_id").reset_index(drop=True)
after   = len(full_df)

if before != after:
    print(f"Warning: dropped {before - after} duplicate patient rows "
          f"({before} -> {after}). "
          "Fix build_multimodal_dataset.py to eliminate these at source.")

full_df.to_csv(CLEAN_CSV, index=False)
print(f"Clean dataset written: {CLEAN_CSV}  ({after} unique patients)")

# ======================
# STEP 2 — BUILD AE GENE CSV
# The autoencoder was pretrained (pretrain_gene_autoencoder.py) on
# 528 patients using the top 2000 genes. It saved the selected gene
# IDs to trained_models/ae_gene_cols.npy. Here we load those IDs,
# filter the 31-patient CLEAN_CSV to only those columns, and write
# AE_CSV. This guarantees the survival model sees exactly the same
# gene features the encoder was trained on, in the same order.
# ======================
AE_GENE_COLS_PATH = "trained_models/ae_gene_cols.npy"
if not os.path.exists(AE_GENE_COLS_PATH):
    raise FileNotFoundError(
        f"{AE_GENE_COLS_PATH} not found. "
        "Run pretrain_gene_autoencoder.py first."
    )

ae_gene_cols = np.load(AE_GENE_COLS_PATH, allow_pickle=True).tolist()

# Map AE gene IDs (version-stripped, e.g. ENSG00000168484) to the
# versioned column names in CLEAN_CSV (e.g. ENSG00000168484.12).
# build_multimodal_dataset.py keeps version suffixes in column names.
clean_gene_cols = [c for c in full_df.columns if c.startswith("ENSG")]
clean_bare      = [c.split(".")[0] for c in clean_gene_cols]
bare_to_versioned = dict(zip(clean_bare, clean_gene_cols))

matched_cols = []
for bare_id in ae_gene_cols:
    versioned = bare_to_versioned.get(bare_id)
    if versioned is not None:
        matched_cols.append(versioned)

if len(matched_cols) == 0:
    raise ValueError(
        "No AE gene IDs matched columns in the clean CSV. "
        "Check that build_multimodal_dataset.py strips version numbers "
        "the same way as pretrain_gene_autoencoder.py."
    )

print(f"AE gene cols matched: {len(matched_cols)} / {len(ae_gene_cols)}")
if len(matched_cols) < len(ae_gene_cols):
    n_missing = len(ae_gene_cols) - len(matched_cols)
    print(f"  Warning: {n_missing} AE genes not found in clean CSV "
          f"(will be zero-padded by LungSurvivalDataset).")

META_COLS = ["patient_id", "OS_months", "event"]
df_ae     = full_df[META_COLS + matched_cols].copy()
df_ae.to_csv(AE_CSV, index=False)
print(f"AE dataset written: {AE_CSV}  "
      f"({len(matched_cols)} genes, {len(df_ae)} patients)")

# ======================
# PATIENT-LEVEL SPLIT
# train_indices derived from dataset.df (after CT validation),
# not full_df, to avoid index-alignment bugs with Subset.
# ======================
if not os.path.exists(CLINICAL_CSV):
    raise FileNotFoundError(
        f"{CLINICAL_CSV} not found. Run build_clinical_features.py first."
    )

print("CT mode: MedicalNet ResNet10 multi-scale (layer2+layer4, frozen)")

# Two dataset instances — same data, different augmentation flags.
# augment=True applies random flips and intensity shifts during training.
# Val and inference always use augment=False.
dataset      = LungSurvivalDataset(AE_CSV, ct_dir, clinical_csv=CLINICAL_CSV,
                                   augment=False)
dataset_aug  = LungSurvivalDataset(AE_CSV, ct_dir, clinical_csv=CLINICAL_CSV,
                                   augment=True)

# Use dataset.df (not full_df) as the source of patient IDs for the split.
# LungSurvivalDataset.__init__ may drop patients whose CT files are missing,
# making dataset.df shorter than full_df. Indexing Subset with full_df indices
# would then reference rows that don't exist in dataset.df.
dataset_df      = dataset.df                          # already CT-validated
valid_patients  = dataset_df["patient_id"].values     # patients with CTs

np.random.seed(42)
shuffled = valid_patients.copy()
np.random.shuffle(shuffled)

n_train        = int(0.7 * len(shuffled))
train_patients = set(shuffled[:n_train])
val_patients   = set(shuffled[n_train:])

# Positional indices into dataset.df (0-based, safe for Subset)
train_indices = dataset_df.index[dataset_df["patient_id"].isin(train_patients)].tolist()
val_indices   = dataset_df.index[dataset_df["patient_id"].isin(val_patients)].tolist()

train_dataset = Subset(dataset_aug, train_indices)  # augmented
val_dataset   = Subset(dataset,     val_indices)    # clean

# ======================
# GENE NORMALISATION STATS (training split only)
# Compute per-gene mean and std from training rows only, then hand them
# to the dataset via set_gene_stats(). This prevents val-set gene
# expression values from leaking into the normalisation used at training.
# ddof=0 (population std) matches numpy behaviour in predict.py.
# ======================
raw_genes   = dataset.get_raw_gene_matrix()          # (n_patients, n_genes)
train_genes = raw_genes[train_indices]               # training rows only

gene_mean = train_genes.mean(axis=0)                 # (n_genes,)
gene_std  = train_genes.std(axis=0)                  # (n_genes,) ddof=0

# Stats are set on BOTH dataset instances.
# dataset_aug is a separate object — it does not share state with dataset,
# so set_gene_stats() must be called on it explicitly.
dataset.set_gene_stats(gene_mean, gene_std)
dataset_aug.set_gene_stats(gene_mean, gene_std)

# Save stats alongside the model so predict.py can load and reuse them,
# guaranteeing identical normalisation at inference time.
os.makedirs("trained_models", exist_ok=True)
np.save("trained_models/gene_mean.npy", gene_mean)
np.save("trained_models/gene_std.npy",  gene_std)
print(f"Gene stats saved  (mean: {gene_mean.shape}, std: {gene_std.shape})")

# Clinical normalisation stats (training split only)
raw_clinical   = dataset.get_raw_clinical_matrix()   # (n_patients, 4)
if raw_clinical is not None:
    train_clinical = raw_clinical[train_indices]
    clin_mean = train_clinical.mean(axis=0)
    clin_std  = train_clinical.std(axis=0)
    dataset.set_clinical_stats(clin_mean, clin_std)
    dataset_aug.set_clinical_stats(clin_mean, clin_std)
    np.save("trained_models/clinical_mean.npy", clin_mean)
    np.save("trained_models/clinical_std.npy",  clin_std)
    print(f"Clinical stats saved (mean: {clin_mean.shape})")
else:
    clin_mean = clin_std = None
    print("Warning: no clinical data loaded")


# Fix: batch_size=2 gave Cox loss almost no usable pairs (25% chance of
# zero-event batches). Use batch_size=8, capped at train set size.
BATCH_SIZE = min(8, len(train_dataset))

# Fix (Loophole 8): drop_last was True, which silently discarded the last
# partial batch every epoch. With only 21 training patients this wastes
# up to 5 patients per epoch (~24% of training data). Changed to False.
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
val_loader   = DataLoader(val_dataset,   batch_size=len(val_dataset), shuffle=False)

# ======================
# DEVICE
# ======================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
print(f"Train patients: {len(train_patients)} | Val patients: {len(val_patients)}")

# ======================
# MEDICALNET CT ENCODER
# Wraps the pretrained ResNet10 from MedicalNet (Tencent).
# Only layer1 + layer2 are used, giving a 128-channel spatial feature map.
# AdaptiveAvgPool3d collapses it to a 128-dim vector matching ct_out_dim.
# All weights are frozen — zero gradient updates during survival training.
# Falls back to the custom 4-block CNN if weights are not found.
# ======================
MEDNET_WEIGHTS = "trained_models/resnet_10_23dataset.pth"

class MedicalNetEncoder(nn.Module):
    """
    Multi-scale frozen ResNet10 encoder pretrained on 23 medical datasets.

    Improvement over the original single-scale encoder:
    Instead of using only layer1+layer2 (which captures only local texture
    at 128-dim), this encoder extracts features at TWO scales:

      Scale 1 — layer2 output (B, 128, 16, 16, 16):
        Local features: tumour boundary texture, spiculation,
        ground-glass opacity, small-scale intensity patterns.

      Scale 2 — layer4 output (B, 512, 4, 4, 4):
        Global features: tumour size relative to anatomy, lymph node
        involvement patterns, pleural contact, vascular invasion.

    Both are global-average-pooled and concatenated -> (B, 640).
    A small trainable projection maps this to (B, ct_out_dim=128).
    All ResNet weights remain frozen — zero overfitting risk from CT.

    Why multi-scale?
    A single scale forces a choice between local detail and global context.
    Multi-scale fusion gives the survival head information at both levels,
    letting the projection layer learn which scale is more prognostically
    relevant for each dimension of the output.
    """
    def __init__(self, weights_path, ct_out_dim=128):
        super().__init__()
        from resnet import resnet10

        base = resnet10(
            sample_input_W=128,
            sample_input_H=128,
            sample_input_D=128,
            shortcut_type="B",
            no_cuda=not torch.cuda.is_available(),
            num_seg_classes=2,
        )
        state = torch.load(weights_path, weights_only=False,
                           map_location="cpu")
        base.load_state_dict(state["state_dict"], strict=False)

        # Shared stem: conv1 -> bn1 -> relu -> maxpool
        self.stem = nn.Sequential(
            base.conv1, base.bn1, base.relu, base.maxpool
        )
        # Four residual stages kept separate so we can tap intermediate outputs
        self.layer1 = base.layer1   # (B, 64,  32, 32, 32)
        self.layer2 = base.layer2   # (B, 128, 16, 16, 16)  <- scale 1
        self.layer3 = base.layer3   # (B, 256,  8,  8,  8)
        self.layer4 = base.layer4   # (B, 512,  4,  4,  4)  <- scale 2

        self.pool = nn.AdaptiveAvgPool3d(1)

        # Freeze ALL encoder weights — no gradient flows through ResNet
        for p in (list(self.stem.parameters()) +
                  list(self.layer1.parameters()) +
                  list(self.layer2.parameters()) +
                  list(self.layer3.parameters()) +
                  list(self.layer4.parameters())):
            p.requires_grad = False

        # Trainable multi-scale projection
        # Concatenated dim: 128 (layer2) + 512 (layer4) = 640
        self.ms_proj = nn.Sequential(
            nn.Linear(128 + 512, ct_out_dim),
            nn.LayerNorm(ct_out_dim),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        # x: (B, 1, 128, 128, 128)
        x = self.stem(x)       # (B, 64,  32, 32, 32)
        x = self.layer1(x)     # (B, 64,  32, 32, 32)
        f2 = self.layer2(x)    # (B, 128, 16, 16, 16)  <- local features
        f3 = self.layer3(f2)   # (B, 256,  8,  8,  8)
        f4 = self.layer4(f3)   # (B, 512,  4,  4,  4)  <- global features

        # Global average pool each scale -> (B, C)
        v2 = self.pool(f2).view(f2.size(0), -1)   # (B, 128)
        v4 = self.pool(f4).view(f4.size(0), -1)   # (B, 512)

        # Concatenate and project -> (B, ct_out_dim)
        ms = torch.cat([v2, v4], dim=1)            # (B, 640)
        return self.ms_proj(ms)                    # (B, 128)


# ======================
# MODEL
# Fix 1: CT encoder was severely underpowered (3,696 params vs 7.7M for genes).
#         Deepened to 4 conv blocks with InstanceNorm (stable at small batch sizes).
# Fix 2: Self-attention on 2 tokens (CT, gene) was equivalent to a learned
#         weighted average — replaced with a proper concat + MLP fusion block.
# Fix 3: Gene encoder now expects reduced gene_dim (run reduce_genes.py first).
#         With 500 genes the model drops from 7.7M to ~65K params, which is
#         appropriate for a dataset of this size.
# ======================
class MultimodalSurvivalModel(nn.Module):
    def __init__(self, gene_dim, latent_dim=32, ct_out_dim=128,
                 fusion_dim=128, clinical_dim=0):
        super().__init__()

        # --- CT branch ---
        # Use pretrained MedicalNet ResNet10 encoder if weights exist,
        # otherwise fall back to the custom 4-block CNN.
        # Both produce a (B, ct_out_dim) = (B, 128) output.
        self._ct_mode = "medicalnet"

        if os.path.exists(MEDNET_WEIGHTS):
            self.ct_encoder    = MedicalNetEncoder(MEDNET_WEIGHTS,
                                                   ct_out_dim=ct_out_dim)
            self._ct_is_frozen = True
            print("CT encoder: MedicalNet ResNet10 multi-scale (layer2+layer4, frozen)")
        else:
            self.ct_encoder = nn.Sequential(
                nn.Conv3d(1,  16, kernel_size=3, stride=2, padding=1),
                nn.InstanceNorm3d(16),
                nn.ReLU(inplace=True),
                nn.Conv3d(16, 32, kernel_size=3, stride=2, padding=1),
                nn.InstanceNorm3d(32),
                nn.ReLU(inplace=True),
                nn.Conv3d(32, 64, kernel_size=3, stride=2, padding=1),
                nn.InstanceNorm3d(64),
                nn.ReLU(inplace=True),
                nn.Conv3d(64, ct_out_dim, kernel_size=3, stride=2, padding=1),
                nn.InstanceNorm3d(ct_out_dim),
                nn.ReLU(inplace=True),
                nn.AdaptiveAvgPool3d(1),
            )
            self._ct_is_frozen = False
            print("CT encoder: custom 4-block CNN (trained from scratch)")

        # --- Gene branch (frozen autoencoder encoder) ---
        # The encoder was pretrained on 528 patients to compress
        # 2000 gene expression values into a 32-dim latent vector.
        # Its weights are loaded and frozen — the survival training
        # does not update them. A small trainable projection then
        # maps the 32-dim latent to ct_out_dim (128) to match the
        # CT branch output dimension entering the gated fusion.
        self.gene_encoder = nn.Sequential(
            nn.Linear(gene_dim, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.2),
            nn.Linear(256, latent_dim),
        )

        # Trainable projection: latent -> ct_out_dim
        # This is the only part of the gene branch that gets updated
        # during survival training.
        self.gene_proj = nn.Sequential(
            nn.Linear(latent_dim, ct_out_dim),
            nn.ReLU(inplace=True),
        )

        # --- Fusion ---
        # Fix: replaced 2-token self-attention (= expensive 2x2 softmax) with
        # a gated fusion: each modality gets its own attention gate so the
        # network can learn how much to trust CT vs genomics per sample.
        self.ct_gate   = nn.Linear(ct_out_dim, ct_out_dim)
        self.gene_gate = nn.Linear(ct_out_dim, ct_out_dim)

        self.fusion = nn.Sequential(
            nn.Linear(ct_out_dim * 2, fusion_dim),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.3),
            nn.Linear(fusion_dim, 1)
        )

        # --- Clinical branch (optional) ---
        # A small MLP handles the 4-dim clinical vector. When clinical_dim=0
        # the branch is skipped entirely and fusion uses only CT + gene.
        self.clinical_dim = clinical_dim
        if clinical_dim > 0:
            self.clinical_encoder = nn.Sequential(
                nn.Linear(clinical_dim, 32),
                nn.ReLU(inplace=True),
                nn.Linear(32, ct_out_dim),
                nn.ReLU(inplace=True),
            )
            self.clin_gate = nn.Linear(ct_out_dim, ct_out_dim)
            # Fusion now takes 3x ct_out_dim instead of 2x
            self.fusion = nn.Sequential(
                nn.Linear(ct_out_dim * 3, fusion_dim),
                nn.ReLU(inplace=True),
                nn.Dropout(p=0.3),
                nn.Linear(fusion_dim, 1)
            )

        # Store modality attention weights for inspection
        self.last_ct_gate   = None
        self.last_gene_gate = None
        self.last_clin_gate = None

    def forward(self, ct, genes, clinical=None):
        # CT branch
        ct_feat = self.ct_encoder(ct.unsqueeze(1))     # (B, ct_out_dim)
        ct_feat = ct_feat.view(ct_feat.size(0), -1)         # (B, ct_out_dim)

        # Gene branch: frozen encoder -> trainable projection
        latent    = self.gene_encoder(genes)                 # (B, latent_dim)
        gene_feat = self.gene_proj(latent)                   # (B, ct_out_dim)

        # Gated fusion
        ct_w   = torch.sigmoid(self.ct_gate(ct_feat))       # (B, ct_out_dim)
        gene_w = torch.sigmoid(self.gene_gate(gene_feat))   # (B, ct_out_dim)

        self.last_ct_gate   = ct_w.detach()
        self.last_gene_gate = gene_w.detach()

        ct_gated   = ct_feat   * ct_w
        gene_gated = gene_feat * gene_w

        if self.clinical_dim > 0 and clinical is not None and clinical.shape[-1] > 0:
            clin_feat = self.clinical_encoder(clinical)          # (B, ct_out_dim)
            clin_w    = torch.sigmoid(self.clin_gate(clin_feat)) # (B, ct_out_dim)
            self.last_clin_gate = clin_w.detach()
            clin_gated = clin_feat * clin_w
            fused = torch.cat([ct_gated, gene_gated, clin_gated], dim=1)  # (B, 3*dim)
        else:
            self.last_clin_gate = None
            fused = torch.cat([ct_gated, gene_gated], dim=1)              # (B, 2*dim)

        return self.fusion(fused)                                          # (B, 1)


# ======================
# COX PARTIAL LIKELIHOOD LOSS
# Fix: original code divided by N (all samples) instead of the number of
# events, diluting the loss proportionally to censoring rate.
# ======================
def cox_loss(pred, time, event):
    pred  = pred.view(-1)
    time  = time.view(-1)
    event = event.view(-1)

    if event.sum() == 0:
        return torch.tensor(0.0, requires_grad=True, device=pred.device)

    # Sort by descending survival time (standard Cox convention)
    order = torch.argsort(time, descending=True)
    pred  = pred[order]
    event = event[order]

    hazard          = torch.exp(pred - pred.max())              # numerical stability
    log_cum_hazard  = torch.log(torch.cumsum(hazard, dim=0) + 1e-8)

    # Fix: sum only over events, divide by event count (not total N)
    event_terms = (pred - log_cum_hazard) * event
    return -event_terms.sum() / (event.sum() + 1e-8)


# ======================
# C-INDEX  (vectorised)
# Original was correct but O(n²) in Python loops.
# Replaced with a vectorised version — same result, much faster.
# ======================
def concordance_index(pred, time, event):
    pred  = pred.view(-1).float()
    time  = time.view(-1).float()
    event = event.view(-1).float()

    # All pairs (i, j) where patient i had event and died before j
    t_i = time.unsqueeze(1)     # (n, 1)
    t_j = time.unsqueeze(0)     # (1, n)
    p_i = pred.unsqueeze(1)
    p_j = pred.unsqueeze(0)
    e_i = event.unsqueeze(1)

    comparable = (t_i < t_j) & (e_i == 1)          # event occurred for i, j lived longer
    concordant = comparable & (p_i > p_j)
    tied_pred  = comparable & (p_i == p_j)

    num_pairs   = comparable.sum().float()
    num_correct = concordant.sum().float() + 0.5 * tied_pred.sum().float()

    return (num_correct / num_pairs).item() if num_pairs > 0 else 0.0


# ======================
# INIT MODEL + OPTIMISER
# Fix: added weight_decay (L2 regularisation) — essential with a small
# dataset to prevent the gene branch from memorising training samples.
# ======================
# Use len(dataset.gene_cols) to get gene_dim — do NOT call dataset[0] here.
# __getitem__ raises RuntimeError if set_gene_stats() has not been called yet.
gene_dim  = len(dataset.gene_cols)
clin_dim  = len(dataset._clinical_cols) if dataset._clinical_df is not None else 0
# Fix (Loophole 11): Always print clinical branch status so you can
# immediately see whether it is active or silently disabled.
if clin_dim == 0:
    print(f"Gene dim: {gene_dim} | Clinical dim: 0")
    print("WARNING: Clinical branch DISABLED — run build_clinical_features.py to enable it.")
else:
    print(f"Gene dim: {gene_dim} | Clinical dim: {clin_dim} — Clinical branch ENABLED")

# Load the pretrained encoder into the model and freeze its weights.
# Parameters with requires_grad=False are skipped by the optimiser,
# so only the gene_proj, ct_encoder, gates, and fusion layers train.
ENCODER_PATH = "trained_models/gene_encoder.pth"
if not os.path.exists(ENCODER_PATH):
    raise FileNotFoundError(
        f"{ENCODER_PATH} not found. "
        "Run pretrain_gene_autoencoder.py first."
    )

model = MultimodalSurvivalModel(
    gene_dim, clinical_dim=clin_dim,
).to(device)

# Load encoder weights (saved as the encoder sub-module state dict)
encoder_state = torch.load(ENCODER_PATH, weights_only=True)
model.gene_encoder.load_state_dict(encoder_state)

# Freeze encoder — these weights will not be updated during survival training
for param in model.gene_encoder.parameters():
    param.requires_grad = False

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
frozen    = sum(p.numel() for p in model.parameters() if not p.requires_grad)
ct_status = "MedicalNet (frozen)" if model._ct_is_frozen else "custom CNN (trainable)"
print(f"CT encoder      : {ct_status}")
print(f"Trainable params: {trainable:,} | Frozen params: {frozen:,}")
optimizer = optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=1e-4, weight_decay=1e-4
)

total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Model parameters: {total_params:,}")

# Scheduler: step every 5 epochs rather than on every val loss plateau,
# giving the optimiser enough runway after each LR reduction.
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

# Early stopping: increased patience to 7 to avoid stopping on val noise
# (val set is small, so C-index can fluctuate significantly).
best_cindex = 0.0
es_patience = 7
es_counter  = 0

# ======================
# TRAINING LOOP
# ======================
MAX_EPOCHS = 50

for epoch in range(MAX_EPOCHS):
    # ---- Train ----
    model.train()
    train_loss = 0.0

    for (ct, genes, clinical), (label, event) in train_loader:
        ct       = ct.float().to(device)
        genes    = genes.float().to(device)
        clinical = clinical.float().to(device)
        time     = label.float().to(device)
        event    = event.float().to(device)

        optimizer.zero_grad()
        output = model(ct, genes, clinical)
        loss   = cox_loss(output, time, event)
        loss.backward()

        # Fix: gradient clipping prevents exploding gradients from the
        # large gene Linear layer during early epochs.
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()
        train_loss += loss.item()

    # ---- Validate ----
    model.eval()
    val_loss = 0.0
    all_preds, all_times, all_events = [], [], []

    with torch.no_grad():
        for (ct, genes, clinical), (label, event) in val_loader:
            ct       = ct.float().to(device)
            genes    = genes.float().to(device)
            clinical = clinical.float().to(device)
            time     = label.float().to(device)
            event    = event.float().to(device)

            output = model(ct, genes, clinical)
            loss   = cox_loss(output, time, event)

            val_loss += loss.item()
            all_preds.append(output.cpu())
            all_times.append(time.cpu())
            all_events.append(event.cpu())

    all_preds  = torch.cat(all_preds)
    all_times  = torch.cat(all_times)
    all_events = torch.cat(all_events)

    c_index = concordance_index(all_preds, all_times, all_events)

    print(
        f"Epoch {epoch+1:03d}/{MAX_EPOCHS} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"C-index: {c_index:.4f} | "
        f"LR: {optimizer.param_groups[0]['lr']:.2e}"
    )

    scheduler.step()

    # Save best model (based on C-index, not val loss)
    if c_index > best_cindex:
        best_cindex = c_index
        es_counter  = 0
        torch.save(model.state_dict(), "trained_models/best_lung_model.pth")
        print(f"  ✅ Best model saved (C-index: {best_cindex:.4f})")
    else:
        es_counter += 1
        if es_counter >= es_patience:
            print(f"  ⛔ Early stopping at epoch {epoch+1} (no improvement for {es_patience} epochs)")
            break

# ======================
# SAVE FINAL MODEL
# ======================
torch.save(model.state_dict(), "trained_models/lung_model.pth")
print(f"\nFinal model saved. Best C-index: {best_cindex:.4f}")

# ======================
# MODALITY GATE INSPECTION
# Replaces the meaningless 2-token attention weights.
# Shows how much the model relied on CT vs genomics for each val patient.
# ======================
model.eval()
(ct, genes, clinical), _ = dataset[0]

ct       = torch.tensor(ct).unsqueeze(0).float().to(device)
genes    = torch.tensor(genes).unsqueeze(0).float().to(device)
clinical = torch.tensor(clinical).unsqueeze(0).float().to(device)

with torch.no_grad():
    _ = model(ct, genes, clinical)

ct_w   = model.last_ct_gate.mean().item()
gene_w = model.last_gene_gate.mean().item()
clin_w = model.last_clin_gate.mean().item() if model.last_clin_gate is not None else 0
total  = ct_w + gene_w + clin_w + 1e-8

print(f"\n🔍 Modality Gates (sample 0):")
print(f"   CT       weight: {ct_w:.4f}  ({ct_w/total:.1%})")
print(f"   Gene     weight: {gene_w:.4f}  ({gene_w/total:.1%})")
print(f"   Clinical weight: {clin_w:.4f}  ({clin_w/total:.1%})")